comics/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, ListView

from comics.models import Comic, Scene
from comics.views import SceneDetailView, ComicDetailView
from endless_pagination.views import AjaxListView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'harpoon.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', AjaxListView.as_view(
                    template_name='scene_list.html',
		    page_template='scene_list_page.html',
                    queryset=Scene.objects.all()),
                name='comics_list'),

    url(r'^(?P<slug>[-\w\d]+)/$', SceneDetailView.as_view(), name="scene_detail"),
    url(r'^(?P<scene>[-\w\d]+)/(?P<slug>[-\w\d]+)/$', ComicDetailView.as_view(), name="comic_detail"),
)
			   

    

harpoon/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, ListView

from endless_pagination.views import AjaxListView
from feeds.models import Post

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'harpoon.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', AjaxListView.as_view(
                    template_name='main.html',
		    page_template='main_page.html',
                    queryset=Post.live.order_by('pub_date')),
                name='front_page'),
    
    
    url(r'^feeds/', include('feeds.urls')),


    url(r'^calendar/', include('local_calendar.urls')),

   
    url(r'^comics/', include('comics.urls')),

    
    url(r'^photologue/', include('photologue.urls')),

    url(r'^search/', include('search.urls')),
    url(r'^test/$', TemplateView.as_view(template_name='test.html')),
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^facebook/', include('django_facebook.urls')),
    url(r'^accounts/', include('django_facebook.auth_urls')),


)

local_calendar/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.timezone import datetime, now, timedelta, utc
from django.db.models import Q
from django.core.urlresolvers import reverse
from localflavor.us.models import USStateField, PhoneNumberField

from calendarium.models import Event, Occurrence
from photologue.models import Photo

from comics.models import Comic

from south.modelsinspector import add_introspection_rules 
add_introspection_rules([], ["^localflavor\.us\.models\.USStateField"])
add_introspection_rules([], ["^localflavor\.us\.models\.PhoneNumberField"])


class Location(models.Model):

    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    website = models.URLField(blank=True)
    phone_number = PhoneNumberField()    
    street_address = models.CharField(max_length=250,)
    city = models.CharField(max_length=250,)
    state = USStateField()
    zipcode = models.CharField(max_length=5,)

    latitude = models.FloatField(blank=True, null=True, editable=False)
    longitude = models.FloatField(blank=True, null=True, editable=False)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return '/events/locations/'+self.slug

    def save(self):
        self.slug = slugify(self.name)
        from geopy import geocoders
        google = geocoders.GoogleV3()
        address, (self.latitude, self.longitude) = google.geocode(' '.join([self.street_address, self.city, self.state, self.zipcode]))
        if address:
            self.street_address, self.city, state_zip, country = address.split(',')
            self.city = self.city[1:]
            waste, self.state, self.zipcode = state_zip.split(' ')
        super(Location, self).save()

    def get_full_address(self):
        address = [self.street_address, self.city + ', ' + self.state + ' ' + self.zipcode]
        return address


class EventModelManager(models.Manager):
    """Custom manager for the ``Event`` model class."""
    def get_occurrences(self, start, end, category=None):
        """Returns a list of events and occurrences for the given period."""
        # we always want the time of start and end to be at 00:00
        start = start.replace(minute=0, hour=0)
        end = end.replace(minute=0, hour=0)
        # if we recieve the date of one day as start and end, we need to set
        # end one day forward
        if start == end:
            end = start + timedelta(days=1)

        # retrieving relevant events
        # TODO currently for events with a rule, I can't properly find out when
        # the last occurrence of the event ends, or find a way to filter that,
        # so I'm still fetching **all** events before this period, that have a
        # end_recurring_period.
        # For events without a rule, I fetch only the relevant ones.
        qs = self.get_query_set()
        if category:
            qs = qs.filter(start__lt=end)
            relevant_events = qs.filter(
                Q(category=category) |
                Q(category__parent=category)
            )
        else:
            relevant_events = qs.filter(start__lt=end)
        # get all occurrences for those events that don't already have a
        # persistent match and that lie in this period.
        all_occurrences = []
        for event in relevant_events:
            all_occurrences.extend(event.get_occurrences(start, end))

        # sort and return
        return sorted(all_occurrences, key=lambda x: x.start)

class ApprovedEventManager(EventModelManager):
    def get_query_set(self):
        return super(ApprovedEventManager,self).get_query_set().filter(approved=True)
 
class OfficialEventManager(ApprovedEventManager):
    def get_query_set(self):
	return super(OfficialEventManager,self).get_query_set().filter(official=True)


class LocalEvent(Event):

    AGE_LIMITS = (
        (1, 'All Ages'),
        (2, '18+'),
        (3, '21+'),
        )

    approved = models.BooleanField()
    location = models.ForeignKey(Location, blank=True, null=True)
    age_limit = models.IntegerField(choices=AGE_LIMITS)
    price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    official = models.BooleanField()
    comics = models.ManyToManyField(Comic, blank=True, null=True)
    banner = models.ForeignKey(Photo)
 
    objects = EventModelManager()
    public = ApprovedEventManager()
    featured = OfficialEventManager()

    def save(self):
        if self.price == None:
            self.price = 0.00
        return super(LocalEvent, self).save()

    def get_absolute_url(self):
        return reverse('calendar_event_detail', kwargs={'pk': self.pk,})

class LocalOccurrence(Occurrence):

    LocalEvent = models.ForeignKey(LocalEvent, related_name='local_occurrences',)
    comics = models.ManyToManyField(Comic, blank=True, null=True)
    banner = models.ForeignKey(Photo)    

    def get_absolute_url(self):
        return reverse('calendar_occurrence_detail', kwargs={
            'pk': self.pk,
            'year': self.start.year,
            'month': self.start.month,
            'day': self.start.day,
            })

harpoon/templates/calendar/base.html
{% extends 'site_base.html' %}

{% block header_links %}{% endblock %}


{% block main %}
            <div id="calendar">
                    {% block calendar %}{% endblock %}
            </div>

{% endblock %}

harpoon/templates/calendar/day.html
{% extends "calendar/base.html" %}



{% block calendar %}
                <div id="day-week-calendar">
                    <div id="calendar-top" class="row">
                        <div id="categories">
                            <ul>
                                <li><p>{% if not current_category %}<strong>{% endif %}<a href=".">All events</a>{% if not current_category %}</strong>{% endif %}</li>
                                {% for category in categories %}
                                <li> • <p>{% if category == current_category %}<strong>{% endif %}<a href=".?category={{ category.pk }}">{{ category.name }}</a>{% if category == current_category %}</strong>{% endif %}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        <form action="." method="post">{% csrf_token %}
                            <input class="btn btn-default" type="submit" name="previous" value="previous" />
                            <input class="btn btn-default" type="submit" name="next" value="next" />
                            <input class="btn btn-default" type="submit" name="today" value="today" />
                        </form> 
                    </div>
                    <div class="week-day" class="row">
                        <div class="week-headers"><a href="{% url "calendar_day" year=day|date:'Y' month=day|date:'m' day=day|date:'d' %}">{{ day|date:'D m/d' }}</a></div>
                        {% for occurrence in occurrences %}
                        <div class="week-event panel panel-default">
                            <a href="{{ occurrence.get_absolute_url }}">
                                <div class="week-event-title"><p>{{ occurrence }} » {{ occurrence.event.localevent.location.name }}</p></div>
                                <div class="week-event-time"><p><strong>{{ occurrence.start|date:"P" }}</strong></p></div>
                            </a>
                        </div>
                        {% empty %}
                        <div class="week-event">
                            <div class="week-event-title"><p>NO LAUGHING!</p></div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

{% endblock %}

harpoon/templates/calendar/event_create.html
{% extends "calendar/base.html" %}

{% block header_links%}
        {{ form.media }}
{% endblock %}


{% block main %}
    <div id="event-form">
        <form action="" method="post">{% csrf_token %}
        {% for field in form %}
            <li class="fieldWrapper">
            {{ field.label_tag }}
            {{ field.errors }}
            {{ field }}
            </li>
            {% endfor %} 
            <input type="submit" value="create" />
        </form>
    </div>
{% endblock %}

harpoon/templates/calendar/event_detail.html
{% extends 'calendar/base.html' %}

{% block main %}
    <div id="event-info">
        <div class="col-md-6 col-xs-12 panel">
            <div id="event-date"><a href="{% url 'calendar_day' year=object.start|date:"Y" month=object.start|date:"m" day=object.start|date:"d" %}">{{ object.start|date:"l M j, Y" }} »</a></div>
            <div id="event-title"{% if object.localevent.fartlyfe_offical %} class="official-event">LEGIT FART LYFE SHIT- {% else %}>{% endif %}{{ object.title }}</div>
            <div id="event-time">{{ object.start|date:"P" }}</div>
            <div id="event-age-limit">{{ object.localevent.get_age_limit_display }}</div>
            <div id="event-price">{% if object.localevent.price %}${{ object.localevent.price }}{% else %}Free{% endif %}</div>
            <div id="event-description">{{ object.description|safe }}</div>
            <div id="event-category">{% if object.category %}{{ object.category }}{% else %}no category{% endif %}</div>
            <a href="javascript:history.back();">back</a>
        </div>
        <div class="col-md-6 col-xs-12">
            {% if object.localevent.location %}
            <div id="event-location" class="col-xs-12 panel">
                <div id="location-title">{{ object.localevent.location.name }}</div>
                <div id="location-website"><a href="{{ object.localevent.location.website }}">website</a></div>
                <div id="location-number">{{ object.localevent.location.phone_number }}</div>
                <div id="location-address">
                {% for piece in object.localevent.location.get_full_address %}
                    <p>{{ piece }}</p>
                {% endfor %}
                </div>
                <div id="location-map" class="map-canvas">
                    {% load location_info %}
                    {{ object.localevent.location|json_info|safe }}
                </div>
            </div>{% endif %}
        </div>
    </div>


{% endblock %}

harpoon/templates/calendar/month.html
{% extends 'calendar/base.html' %}

 
{% block calendar %}
        <h1>{{ date|date:"F Y" }}</h1>
        <div id="calendar-top">
            <div id="categories">
                <ul>
                    <li>{% if not current_category %}<strong>{% endif %}<a href=".">All events</a>{% if not current_category %}</strong>{% endif %}</li>
                    {% for category in categories %}
                    <li> • {% if category == current_category %}<strong>{% endif %}<a href=".?category={{ category.pk }}">{{ category.name }}</a>{% if category == current_category %}</strong>{% endif %}</li>
                    {% endfor %}
                </ul>
            </div>
            <form action="." method="post">{% csrf_token %}
                <input type="submit" name="previous" value="previous" />
                <input type="submit" name="next" value="next" />
                <input type="submit" name="today" value="today" />
            </form> 
        </div>
        <div id="month-calendar">
            <div id="month-header">
                <div class="calendar-headers month-day left-column"></div>
                <div class="calendar-headers month-day">sunday</div>
                <div class="calendar-headers month-day">monday</div>
                <div class="calendar-headers month-day">tuesday</div>
                <div class="calendar-headers month-day">wednesday</div>
                <div class="calendar-headers month-day">thursday</div>
                <div class="calendar-headers month-day">friday</div>
                <div class="calendar-headers month-day">saturday</div>
            </div>
            {% load local_calendar_tags %}
            {% for week in month %}
            {% if week %}
            <div class="month-week">
                <div class="month-day left-column"><a href="{{ date|get_week_URL:week.0.0 }}">see all week</a></div>
                {% for day, occurrences, current in week %}
                    <div class="month-day">
                    {% if day != 0 %}
                        {% if current %}<strong>{% endif %}<a href="{% url "calendar_day" year=date|date:"Y" month=date|date:"m" day=day %}">{{ day }}</a>{% if current %}</strong>{% endif  %}
                        {% for occurrence in occurrences %}
                            <p><a href="{{ occurrence.get_absolute_url }}">{{ occurrence.start|date:'P' }}»</br> {{ occurrence }}</a></p>
                        {% endfor %}
                    {% endif %}
                    </div>
                {% endfor %}
            </div>
            {% endif %}
            {% endfor %}
        </div>


{% endblock %}
 

harpoon/templates/calendar/occurrence_detail.html
{% extends 'calendar/base.html' %}

{% block main %}
    <div id="event-info">
        <div id="event-left" class="panel panel-default col-md-6">
            <div id="event-date"><p><a href="{% url 'calendar_day' year=occurrence.start|date:"Y" month=occurrence.start|date:"m" day=occurrence.start|date:"d" %}">{{ occurrence.start|date:"l M j, Y" }} »</a></div>
            <div id="event-title"{% if occurrence.event.localevent.offical %} class="official-event">HARPOON PRESENTS - {% else %}>{% endif %}<p>{{ occurrence.title }}</p></div>
            <div id="event-time"><p>{{ occurrence.start|date:"P" }}</p></div>
            <div id="event-age-limit"><p>{{ occurrence.event.localevent.get_age_limit_display }}<p></div>
            <div id="event-price"><p>{% if occurrence.event.localevent.price %}${{ occurrence.event.localevent.price }}{% else %}Free{% endif %}</p></div>
            <div id="event-description"><p>{{ occurrence.description|safe }}</p></div>
	    {% if occurrence.localoccurrence.comics.all %}<h5>With {% for comic in occurrence.localoccurrence.comics.all %}<a href="{{ comic.get_absolute_url }}">{{ comic.user.get_full_name }}</a> {% endfor %}</h5>{% endif %}
        </div>
        <div class="col-md-6 col-xs-12">
            {% if occurrence.event.localevent.location %}
            <div id="event-location" class="panel panel-default">
                <div id="location-title"><p>{{ occurrence.event.localevent.location.name }}</p></div>
                {% if occurrence.event.localevent.location.website %}
                <div id="location-website"><p><a href="{{ occurrence.event.localevent.location.website }}">website</a></p></div>
                {% endif %}
                {% if occurrence.event.localevent.location.phone_number %}
                <div id="location-number"><p>{{ occurrence.event.localevent.location.phone_number }}</p></div>
                {% endif %}
                <div id="location-address">
                {% for piece in occurrence.event.localevent.location.get_full_address %}
                    <p>{{ piece }}</p>
                {% endfor %}
                </div>
                <div id="location-map" class="map-canvas">
                    {% load location_info %}
                    {{ occurrence.event.localevent.location|json_info|safe }}
                </div>
            </div>{% endif %}
        </div>
    </div>


{% endblock %}

harpoon/templates/calendar/week.html
{% extends 'calendar/base.html' %}


{% block calendar %}
                <div id="day-week-calendar">
                    <div id="calendar-top">
                        <div id="categories">
                            <ul>
                                <li>{% if not current_category %}<strong>{% endif %}<a href=".">All events</a>{% if not current_category %}</strong>{% endif %}</li>
                                {% for category in categories %}
                                <li> • {% if category == current_category %}<strong>{% endif %}<a href=".?category={{ category.pk }}">{{ category.name }}</a>{% if category == current_category %}</strong>{% endif %}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        <form action="." method="post">{% csrf_token %}
                            <input type="submit" name="previous" value="previous" />
                            <input type="submit" name="next" value="next" />
                            <input type="submit" name="today" value="today" />
                        </form> 
                    </div>
                    <div class="calendar-week">
                    {% for date, occurrences, hours_list, current in week %}
                        <div class="week-day">
                            <div class="week-headers"><a href="{% url "calendar_day" year=date|date:'Y' month=date|date:'m' day=date|date:'d' %}">{{ date|date:'D m/d' }}</a></div>
                            {% for occurrence in occurrences %}
                            <div class="week-event">
                                <a href="{{ occurrence.get_absolute_url }}">
                                    <div class="week-event-title">{{ occurrence }} » {{ occurrence.event.localevent.location.name }}</div>
                                    <div class="week-event-time">{{ occurrence.start|date:"P" }}</div>
                                </a>
                            </div>
                            {% empty %}
                            <div class="week-event">
                                <div class="week-event-title">nothing today folks</div>
                            </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    </div>
                </div>
{% endblock %}