comics/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, ListView

from comics.models import Comic, Scene
from comics.views import SceneDetailView, ComicDetailView
from endless_pagination.views import AjaxListView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'harpoon.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', AjaxListView.as_view(
                    template_name='scene_list.html',
		    page_template='scene_list_page.html',
                    queryset=Scene.objects.all()),
                name='comics_list'),

    url(r'^(?P<slug>[-\w\d]+)/$', SceneDetailView.as_view(), name="scene_detail"),
    url(r'^(?P<scene>[-\w\d]+)/(?P<slug>[-\w\d]+)/$', ComicDetailView.as_view(), name="comic_detail"),
)
			   

    

harpoon/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, ListView

from endless_pagination.views import AjaxListView
from feeds.models import Post

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'harpoon.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', AjaxListView.as_view(
                    template_name='main.html',
		    page_template='main_page.html',
                    queryset=Post.live.order_by('pub_date')),
                name='front_page'),
    
    
    url(r'^feeds/', include('feeds.urls')),


    url(r'^calendar/', include('local_calendar.urls')),

   
    url(r'^comics/', include('comics.urls')),

    
    url(r'^photologue/', include('photologue.urls')),

    url(r'^search/', include('search.urls')),
    url(r'^test/$', TemplateView.as_view(template_name='test.html')),
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^facebook/', include('django_facebook.urls')),
    url(r'^accounts/', include('django_facebook.auth_urls')),


)

feeds/models.py
import datetime
import os
import audioread

from django.db import models
from django.db.models import Q
from django.template.defaultfilters import slugify
from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from tinymce.models import HTMLField
from photologue.models import Gallery, Photo
from tagging.fields import TagField
from tagging.managers import ModelTagManager, ModelTaggedItemManager
from colorfield.fields import ColorField
from comics.models import Comic
 
from south.modelsinspector import add_introspection_rules
add_introspection_rules([], ["^colorfield\.fields\.ColorField"])

def content_file_name(instance, filename):
    today = datetime.datetime.strftime(datetime.datetime.now(), '%Y/%m/%d')
    file_name = '/'.join(['content', os.path.splitext(filename)[1][1:], today, filename])
    if len(file_name) > 255:
        return file_name[:255]
    else:
        return file_name


class PublicFeedManager(models.Manager):
    def get_queryset(self):
        return super(PublicFeedManager,self).get_query_set().filter(public=True)
 

class Feed(models.Model):
    
    objects = models.Manager()
    published = PublicFeedManager()
    
    title = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    slug = models.SlugField(unique=True, help_text="Automatically comes from title. Must be unique.", blank=True, editable=False)
    description = HTMLField()
    image = models.ForeignKey(Photo, blank=True, null=True, on_delete=models.SET_NULL)
    authors = models.ManyToManyField(User)
    public = models.BooleanField(default=False)
    color = ColorField(blank=True, null=True)

    #Podcast Info
    is_audio_podcast = models.BooleanField(default=False)
    is_video_podcast = models.BooleanField(default=False)
    copyright = models.CharField(max_length=250, blank=True, editable=False)
    summary = models.CharField(max_length=250, blank=True, editable=False)
    explicit = models.BooleanField(default=False)
    itunes_link = models.URLField(max_length=250, blank=True)
    copyright = models.CharField(max_length=250, blank=True)
    block = models.BooleanField(default=False)
    complete = models.BooleanField(default=False)

    class Meta:
        ordering = ['title']

    def save(self):
        self.slug = slugify(self.title)
        super(Feed, self).save()

    def __unicode__(self):
        return unicode(self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('posts_by_feed', (), {'slug': self.slug })

    def live_entry_set(self):
        from apps.feeds.models import Post
        return self.entry_set.filter(status=Post.LIVE_STATUS)


class Topic(models.Model):

    title = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    slug = models.SlugField(unique=True, help_text="Automatically comes from title. Must be unique.", blank=True, editable=False)
    description = HTMLField()
    image = models.ForeignKey(Photo, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['title']

    def save(self):
        self.slug = slugify(self.title)
        super(Topic, self).save()

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('topic_detail', (), {'slug': self.slug })
    
    def live_entry_set(self):
        from apps.feeds.models import Post
        return self.entry_set.filter(status=Post.LIVE_STATUS)


class LivePostManager(models.Manager):
    def get_query_set(self):
        return super(LivePostManager,self).get_query_set().filter(Q(status=self.model.LIVE_STATUS),Q(pub_date__lte=datetime.datetime.now()),Q(feed__public=True))


class Post(models.Model):
    LIVE_STATUS = 1
    SUBMITTED_STATUS = 2
    DRAFT_STATUS = 3
    STATUS_CHOICES = (
        (LIVE_STATUS, 'Live'),
        (SUBMITTED_STATUS, 'Submitted'),
        (DRAFT_STATUS, 'Draft'),)

    
    live = LivePostManager()
    objects = models.Manager()
    tags = ModelTagManager()
    tagged = ModelTaggedItemManager()

    feed = models.ForeignKey(Feed)
    status = models.IntegerField(choices=STATUS_CHOICES, default=LIVE_STATUS)
    title = models.CharField(max_length=250)
    body = HTMLField()
    summary = models.CharField(max_length=250)
    pub_date = models.DateTimeField(default=datetime.datetime.now)
    pub_date_year = models.DateField(editable=False, default=datetime.datetime.now().year)
    posted = models.DateTimeField(default=datetime.datetime.now, editable=False)
    slug = models.SlugField(unique_for_date='pub_date', blank=True, editable=False)
    topics = models.ManyToManyField(Topic, blank=True)
    cover = models.ForeignKey(Photo)
    gallery = models.ForeignKey(Gallery, blank=True, null=True, default=None)
    tags = TagField(help_text="Seperate with spaces. Put multi-word tags in quotes.", verbose_name='tags')
    featured = models.BooleanField(default=False)
    comics = models.ManyToManyField(Comic, blank=True, null=True)

    #Media
    media = models.FileField(upload_to=content_file_name, blank=True, null=True)

    #Podcast-specific info
    explicit = models.BooleanField(default=False)
    description = models.CharField(max_length=250, blank=True)
    mimetype = models.CharField(max_length=250, blank=True, editable=False)
    duration = models.CharField(max_length=250, blank=True, editable=False)
    block = models.BooleanField(default=False)

    class Meta:
        ordering = ['-pub_date']
        permissions = (('can_publish_entry', 'Can publish entry'), ('can_publish_front', 'Can post on front page'))
    
    def save(self):
        self.pub_date_year = self.pub_date.date()
        self.slug = slugify(self.title)
        if len(self.slug) > 50:
            self.slug = self.slug[:49]
        if self.media:
            import mimetypes
            self.mimetype = mimetypes.guess_type(self.media.name)[0]
        if 'audio' in self.mimetype:
            import audioread
            #self.duration = unicode(int(audioread.audio_open(self.media.path).duration))
        elif ('video' in self.mimetype) and self.media:
            import subprocess
            process = subprocess.Popen(['/usr/bin/ffmpeg', '-i', self.media.path], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            stdout, stderr = process.communicate()
            matches = re.search(r"Duration:\s{1}(?P\d+?):(?P\d+?):(?P\d+\.\d+?),", stdout, re.DOTALL).groupdict()
 
            hours = Decimal(matches['hours'])
            minutes = Decimal(matches['minutes'])
            seconds = Decimal(matches['seconds'])
 
            total = 0
            total += 60 * 60 * hours
            total += 60 * minutes
            total += seconds 
            self.duration = total
        return super(Post, self).save()

    def __unicode__(self):
        return unicode(self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('post_detail', (), { 'feed': self.feed.slug,
                                        'year': self.pub_date.strftime("%Y"),
                                        'month': self.pub_date.strftime("%b").lower(),
                                        'day': self.pub_date.strftime("%d"),
                                        'slug': self.slug })

harpoon/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>harpoon presents</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load bootstrap3 %}
        {% bootstrap_css %}
        {% load staticfiles %}
        {% block header_links %}{% endblock %}
        <link href="{% static 'css/harpoon.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body style="background-color:{% block background_color %}#0d1a24{% endblock %}">
        <div class="container">
            <header>
                <div class="row">
                    <div class="col-md-4">
			<a href="/">
			    <img class="col-xs-12" src="http://dfr1ie9bx00ol.cloudfront.net/media/photologue/photos/site_logo.png">
			</a>
		    </div>
		    <div class="col-md-8">
			{% block header_image %}
                        {% endblock %}
		    </div>
                </div>
		<div class="row">
		    <div class="col-xs-12">
			<ul class="nav-list">
				<a href="{% url 'listen_feeds' %}"><li><h3>podcasts</h3></li></a>
				<a href="{% url 'watch_feeds' %}"><li><h3>videos</h3></li></a>
				<a href="{% url 'calendar_current_month' %}"><li><h3>shows</h3></li></a>
				<a href="{% url 'comics_list' %}"><li><h3>comics</h3></li></a>
		        	<li>
            			  <div class="panel panel-default">
                			<div class="panel-header">
                    				<h5 class="panel-title">search</h5>
                			</div>
            			  </div>
				</li>
			</ul>
    	             </div>
          	</div>
            </header>
            {% block center_block %}
            {% endblock %}
        </div> 
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        {% bootstrap_javascript %}
        <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAhTLTDTMlPTop5wkX34vIzN1ZlWndWho0&sensor=false"></script>
    	<script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
    	<script>
            $.endlessPaginate({
            	paginateOnScroll: true,
            	paginateOnScrollMargin: 500
        	});
    	</script>
        <script src="{% static 'js/harpoon.js' %}"></script>
        {% block bottomjs %}{% endblock %}
    </body>
</html>
                    

harpoon/templates/error.html
{% extends 'base.html' %}

{% block center %}
 
	<h3>There's something wrong.</h3>

	<h2>{% block error %}{% endblock %}</h2>
 
{% endblock %}

harpoon/templates/header_image.html
<a href="{{ link }}">
	<img class="col-xs-12 calendar-image" src="{{ image }}" alt="{{ description }}">
</a>

harpoon/templates/main.html
{% extends 'site_base.html' %}

{% block header_image %}
{% load harpoon_tags %}
{% get_header_image %}
{% endblock %}


{% block main %}
    <h1>yeah?</h1>
    {% load endless %}
    {% lazy_paginate object_list %}
    {% for post in object_list %}
    <div class="panel panel-default">
        <div class="panel-header">
            <h4 class="panel-title">{{ post.title }}
        </div>
        <div class="panel-body">
            <p>{{ post.pub_date|date:"N j" }}</p>
            {{ post.body|safe }}
        </div>
    </div>
    {% endfor %}
    {% show_more %}


{% endblock %}

harpoon/templates/main_page.html
    {% load endless %}
    {% lazy_paginate object_list %}
    {% for post in object_list %}
    <div class="panel panel-default">
        <div class="panel-header">
            <h4 class="panel-title">{{ post.title }}
        </div>
        <div class="panel-body">
            <p>{{ post.pub_date|date:"N j" }}</p>
            {{ post.body|safe }}
        </div>
    </div>
    {% endfor %}
    {% show_more %}

harpoon/templates/site_base.html
{% extends 'base.html' %}

{% block center_block %}
    <div class="row">
        <div class="col-md-9">
            {% block main %}
            {% endblock %}
        </div>
        <div class="col-md-3">
            <a href="http://www.facebook.com/harpoonpresents"><img src="http://harpoonpresents.com/media/photologue/photos/f_logo_40px.gif" alt="Facebook"/></a>
            </br>
            <a href="http://www.twitter.com/harpoonpresents"><img src="http://harpoonpresents.com/media/photologue/photos/Twitter40px.png" alt="Twitter"/></a>
            <div class="panel panel-default">
                <div class="panel-header">
                    <h5 class="panel-title">shows soon</h5>
                    {% load local_calendar_tags %}
                    {% render_upcoming_events event_amount=5 %}
                </div>
            </div>
            {% for feed in recent_feeds %}
            <div class="panel panel-default">
                <div class="panel-header">
                    <a href="{{ feed.get_absolute_url }}"><h4 class="panel-title">{{ feed.title }}</h4></a>
                </div>
                <div class="panel-body" style="backround-color:{{ feed.color }}">
                    <ul>
                    {% for post in feed.post_set.all %}
                    <li>
                    <a href="{{ post.get_absolute_url }}">
                        <h5>{{ post.title }}</h5>
                    </a>
                    </li>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
            <div class="panel panel-default">
                <a href="/about/">
                    <h5 class="panel-title">about</h5>
                </a>
            </div>
        </div>
    </div>

{% endblock %}

harpoon/templates/test.html
at least this works